module TwitterServiceApp{
    typedef string Username;
    typedef string Password;
    typedef string TweetText;

    interface TwitterService{
        string ping();
        string getMyInfo();
        string getUserInfo(in Username username);
        string postTweet(in TweetText tweetText);
        string getFeed();
        string connect(in Password password, in Username username);
        oneway void shutdown();
    };
};