module TwitterServiceApp{
    interface TwitterService{
        string ping();
        string getUserInfo(String username, String password);
        string postTweet(String username, String password, String tweet);
        int createAccount(String username, String password);
        int connect(String username, String password);
        oneway void shutdown();
    };
};