package therealtwitter.CORBA.TwitterServiceApp;

/**
* therealtwitter/CORBA/TwitterServiceApp/TwitterServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TwitterService.idl
* jeudi 21 juin 2018 22 h 39 CEST
*/

public final class TwitterServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public therealtwitter.CORBA.TwitterServiceApp.TwitterService value = null;

  public TwitterServiceHolder ()
  {
  }

  public TwitterServiceHolder (therealtwitter.CORBA.TwitterServiceApp.TwitterService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = therealtwitter.CORBA.TwitterServiceApp.TwitterServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    therealtwitter.CORBA.TwitterServiceApp.TwitterServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return therealtwitter.CORBA.TwitterServiceApp.TwitterServiceHelper.type ();
  }

}
