package therealtwitter.CORBA.TwitterServiceApp;


/**
* therealtwitter/CORBA/TwitterServiceApp/TwitterServiceApp/TwitterService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TwitterService.idl
* mercredi 20 juin 2018 00 h 12 CEST
*/

public interface TwitterService extends TwitterServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TwitterService
