package therealtwitter.CORBA.TwitterServiceApp;


/**
* TwitterServiceApp/TwitterServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TwitterService.idl
* lundi 4 juin 2018 14 h 06 CEST
*/

abstract public class TwitterServiceHelper
{
  private static String  _id = "IDL:TwitterServiceApp/TwitterService:1.0";

  public static void insert (org.omg.CORBA.Any a, TwitterService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TwitterService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TwitterServiceHelper.id (), "TwitterService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TwitterService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TwitterServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TwitterService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TwitterService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TwitterService)
      return (TwitterService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _TwitterServiceStub stub = new _TwitterServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TwitterService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TwitterService)
      return (TwitterService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _TwitterServiceStub stub = new _TwitterServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
