package therealtwitter.CORBA.TwitterServiceApp;


/**
* therealtwitter/CORBA/TwitterServiceApp/TwitterService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TwitterService.idl
* vendredi 22 juin 2018 23 h 10 CEST
*/

public interface TwitterService extends TwitterServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TwitterService
