package therealtwitter.CORBA.TwitterServiceApp;

/**
* TwitterServiceApp/TwitterServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TwitterService.idl
* lundi 4 juin 2018 14 h 06 CEST
*/

public final class TwitterServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public TwitterService value = null;

  public TwitterServiceHolder ()
  {
  }

  public TwitterServiceHolder (TwitterService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TwitterServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TwitterServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TwitterServiceHelper.type ();
  }

}
