package therealtwitter.CORBA.TwitterServiceApp;


/**
* therealtwitter/CORBA/TwitterServiceApp/TwitterServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TwitterService.idl
* vendredi 22 juin 2018 23 h 10 CEST
*/

public interface TwitterServiceOperations 
{
  String ping ();
  String getUserInfo (String username);
  String postTweet (String tweetText, String username, double privateKey);
  String getFeed (String username);
  double connect (String password, String username);
  String follow (String username, double privateKey, String secondUser);
  String unfollow (String username, double privateKey, String secondUser);
  boolean isFollowing (String username, String secondUser);
  String getAllUsers ();
  void shutdown ();
} // interface TwitterServiceOperations
