package therealtwitter.CORBA.TwitterServiceApp;


/**
* therealtwitter/CORBA/TwitterServiceApp/TwitterServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TwitterService.idl
* jeudi 21 juin 2018 22 h 39 CEST
*/

public interface TwitterServiceOperations 
{
  String ping ();
  String getUserInfo (String username);
  String postTweet (String tweetText, String username, double privateKey);
  String getFeed (String username);
  double connect (String password, String username);
  String follow (String username, double privateKey, String secondUser);
  void shutdown ();
} // interface TwitterServiceOperations
