package therealtwitter.Client.CORBA.TwitterServiceApp;


/**
* TwitterServiceApp/TwitterServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TwitterService.idl
* lundi 4 juin 2018 14 h 06 CEST
*/

public interface TwitterServiceOperations 
{
  String ping ();
  void shutdown ();
} // interface TwitterServiceOperations
